# Generated by Django 4.1.1 on 2023-02-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
