# Generated by Django 4.1.1 on 2023-02-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_App', '0005_notice_to_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice_to_students',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
