# Generated by Django 4.1.1 on 2023-02-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0003_alter_studentprofile_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
