# Generated by Django 4.1.1 on 2023-02-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0004_alter_user_is_student_alter_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='student_profile'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='teacher_profile'),
        ),
    ]
