# Generated by Django 4.1.1 on 2023-02-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0007_alter_message_user_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.FileField(blank=True, upload_to='student_assignments'),
        ),
    ]
